FROM php:8.2-apache

RUN docker-php-ext-install mysqli

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

WORKDIR /var/www/html

COPY . .

RUN chown -R www-data:www-data /var/www/html && \
    chmod -R 755 /var/www

RUN rm -f index.html && \
    rm -rf /var/www/html/install && \
    rm -rf /var/www/html/db

USER www-data

EXPOSE 80